title: Ali Ahmed Habib
description: >-
  <a href="https://www.linkedin.com/in/ali-ahmed-habib-8483371b0/" target="_blank">LinkedIn</a> 
  <br>
  <a href="mailto:eng.ali.ahmed00@gmail.com"><img src="https://img.shields.io/badge/Gmail-Contact-red"/></a>
  <br>
  <a href="https://www.datacamp.com/portfolio/ah2966629" target="_blank">DataCamp</a>
  <br>
  <a href="https://leetcode.com/u/Ali2222/" target="_blank">Leetcode</a>
  <br>
  <a href="https://www.hackerrank.com/profile/ah2966629" target="_blank">HackerRank</a>  
logo: "/image.png"
show_download: true
theme: jekyll-theme-minimal
