title: Ali Ahmed Habib
description: <a href="https://www.linkedin.com/in/ali-ahmed-habib-8483371b0/" target="_blank">LinkedIn</a> 
<a href="https://leetcode.com/u/Ali2222/" target="_blank">Leetcode</a>
logo: "/image.png"
show_download: true
theme: jekyll-theme-minimal
